### ISSUE TITLE
Setup network and power connections in 3DEN Editor by using "synced with"-functionality

### ISSUE THREAD

**Issue by y0014984** [y0014984/Advanced-Equipment#75]

**Comment by Walthzer** [comment]
Your discord is fully German and I am a bit rusty, so I'll use this instead to suggest this.

Instead of using syncing you could looking into implementing custom Eden connections. AFAIK nobody has done this besides me but its definitely possible and very suited for this application. 

[Example of custom connections](https://youtu.be/wxDjm5ZzwHo)

[A working implementation](https://github.com/Walthzer/RID/tree/rid-eden-compatibility/addons/eden)

Anyway, awesome mod. Hope you guys continue.

**Comment by y0014984** [comment]
Looks very interesting. We will discuss this. Thank you.

**Comment by y0014984** [comment]
https://community.bistudio.com/wiki/Eden_Editor:_Custom_Connections

**Comment by Walthzer** [comment]
Ah they had it fixed. Good to know. Disregard my method then, its ugly compared to native! XD

**Comment by y0014984** [comment]
@Walthzer The Wiki page is very misleading. I needed to look onto your code. In their example the "data" property is missing and throws an error, if I use it as it is. So your code is very helpful.

**Comment by y0014984** [comment]
solved via #295
